export default {
  header: {
    padding: "4px 16px",
  },
  container: {
    fontSize: 11,
    fontWeight: "bold",
    color: "rgba(255,255,255,.7)",
    padding: "6px 16px",
    display: "flex",
    flexDirection: "column",
    gap: "17px",

    "& .action-button": {
      padding: 0,
    },
    "& .icon": {
      width: 18,
      height: 18,
    },
    "& .icon2": {
      opacity: 0.8,
      width: 24,
      height: 24,
      transition: "200ms opacity",
      "&:hover": {
        cursor: "pointer",
        opacity: 1,
      },
    },
    "& .search-box": {
      height: "32px",
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      padding: "6px 16px",
      borderRadius: "8px",
      boxShadow: "0 4px 10.8px 0 rgba(0, 0, 0, 0.02)",
      border: "solid 1px #dedeec",
      backgroundColor: "#fff",
      color: "#40405b",
    },
    "& input": {
      fontSize: "12px",
      fontWeight: "500",
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: "1.67",
      letterSpacing: "normal",
      textAlign: "left",
    },
  },
  row: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "2px 6px",
    cursor: "pointer",
    borderRadius: 6,
    "&.header:hover": {
      backgroundColor: "rgba(255,255,255,.1)",
    },
    "&.highlighted": {
      backgroundColor: "rgba(0,0,0,.05)",
      color: "rgba(255,255,255,1)",
      "& *": {
        fontWeight: 700,
      },
    },
    "&:hover": {
      backgroundColor: "rgba(0,0,0,.05)",
      color: "rgba(255,255,255,1)",
    },
    "& .action": {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
      color: "#40405b",
    },
  },
  tagWrapper: {
    display: "flex",
    flex: 1,
    alignItems: "flex-start",
  },
  chip: {
    height: "24px",
    flexGrow: "0",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: "4px",
    padding: "4px 8px 4px 6px",
    borderRadius: "8px",
    boxShadow: "0 1px 2px -1px rgba(17,12,34,0.05)",
    backgroundColor: "#f5a",
    gap: "4px",
    "& .color": {
      borderRadius: 4,
      width: 8,
      height: 8,
      backgroundColor: "#fff",
    },
    "& .text": {
      fontSize: "12px",
      fontWeight: "600",
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: "1.33",
      letterSpacing: "normal",
      textAlign: "left",
      color: "#fff",
    },
	},
	childChip: {
    display: "flex",
    flexDirection: "row",
    padding: 2,
    borderRadius: 2,
    paddingLeft: 4,
    paddingRight: 4,
		alignItems: "center",
		gap: 6,
    "& .child-color": {
      borderRadius: 5,
      width: 10,
      height: 10,
    },
		"& .child-text": {
			color: "#000"
		},
  },
  expandButton: {
    padding: "0 !important",
    width: 24,
    height: 24,
    "& .icon": {
      marginTop: 0,
      width: 15,
      height: 15,
      transition: "500ms transform",
      transform: "rotate(0deg)",
      "&.expanded": {
        transform: "rotate(90deg)",
      },
    },
  },
  groupWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  childContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    paddingLeft: "30px",
    marginBottom: "17px",
  },
  customIcon: {
    padding: "0 !important",
    width: 30,
    height: 30,
    "& .icon2": {
      width: 24,
      height: 24,
    },
  },
}
