import { grey } from "@mui/material/colors"

export default {
  container: {
    display: "flex",
    flexGrow: 1,
    flexDirection: "column",
    height: "100%",
    maxHeight: "100vh",
    backgroundColor: "#fff",
    overflow: "hidden",
    "&.fullscreen": {
      position: "absolute",
      zIndex: 99999,
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
    },
  },
  headerTitle: {
    fontWeight: "bold",
    color: "#fff",
    paddingLeft: 16,
    fontSize: 22,
  },
  saveContainer: {
    position: "absolute",
    left: 59,
    top: 78,
    borderRadius: 8,
    boxShadow: "0 0 10px 0 rgba(0,0,0,.5)",
    padding: "8px 16px",
    textAlign: "center",
    zIndex: 1001,
    border: "solid 1px rgba(255,255,255,.2)",
    fontWeight: 700,
  },
  headerLeftContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    "& .drop-down": {
      height: "32px",
      flexGrow: "0",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      padding: "8px 10px",
      borderRadius: "8px !important",
      boxShadow: "0 1px 2px -1px rgba(17, 12, 34, 0.08)",
      border: "solid 1px #dedeec",
      gap: "20px",
    },
    "& .drop-down-content": {
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      gap: "8px",
      fontSize: "12px",
      fontWeight: "normal",
      fontStretch: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      textAlign: "left",
      color: "#14142a",
    },
    "& .avatar": {
      width: "16px",
      height: "16px",
      borderRadius: "8px",
      backgroundColor: "#cab9d0",
    },
    "& .spacer": {
      height: "15px",
      borderLeft: "1px solid #14142a",
    },
  },
  footerContainer: {
    overflow: "auto",
    whiteSpace: "nowrap",
    padding: "15px",
    "& .footer-item": {
      width: "368px",
      height: "104px",
      display: "inline-block",
      padding: "16px",
      borderRadius: "8px",
      boxShadow: "0 10px 20px 0 rgba(37, 37, 37, 0.1)",
      // border: "solid 1px #5050ff",
      border: "solid 1px #dedeec",
      backgroundColor: "#fff",
      marginRight: "16px",

      fontSize: "14px",
      fontWeight: "500",
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      textAlign: "left",
      color: "#40405b",
    },
    "& .flex-content": {
      display: "flex",
      flexDirection: "column",
      gap: "16px",
    },
    "& .flex-row": {
      display: "flex",
      flexDirection: "row",
      gap: "16px",
    },
    "& .img-tag": {
      width: "80px",
      height: "32px",
      flexGrow: "0",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: "10px",
      padding: "10px",
      borderRadius: "8px",
      border: "solid 1px #dedeec",
      backgroundColor: "#f4f5f9",
    },
    "& .task-content": {
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
    },
    "& .task-info": {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    "& .task-info-item": {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      gap: "8px",
      fontSize: "16px",
      fontWeight: "bold",
      color: "#40405b",
    },
  },
}
